### ISSUE TITLE
ember generate failure - Unexpected identifier

### ISSUE THREAD

**Issue by ngtjah** [amkirwan/ember-token-auth#8]
Hi,  I was able to install it, but the generate command failed.

≻ ember --version
ember-cli: 2.10.0
node: 6.9.2
os: darwin x64

≻ npm install --save-dev ember-token-auth
ember-home-pager-api@0.0.0 /Users/xxxx/Projects/ember-home_pager_api
└── ember-token-auth@3.0.3-beta

≻ ember generate ember-token-auth
Unexpected identifier
/Users/xxxx/Projects/ember-home_pager_api/node_modules/ember-token-auth/blueprints/ember-token-auth/index.js:8
  afterUninstall: function() {
  ^^^^^^^^^^^^^^
SyntaxError: Unexpected identifier
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Function.Blueprint.load (/Users/xxxx/Projects/ember-home_pager_api/node_modules/ember-cli/lib/models/blueprint.js:1278:29)
    at Function.Blueprint.lookup (/Users/xxxx/Projects/ember-home_pager_api/node_modules/ember-cli/lib/models/blueprint.js:1255:24)

**Comment by amkirwan** [comment]
There is a missing comma in the blueprint which is causing the failure. I'll publish beta shortly.

**Comment by amkirwan** [comment]
Just published an update to 3.0.4-beta. The blueprint should be working now.
